port: 3001

settings:
  openapi:
    useHooks: true
  session:
    secret: 'my secret'
  staticPath: 'public/'
  disk:
    driver: 'local'
    local:
      directory: 'uploaded'
  social:
    secret: 
      codeVerifierSecret: 'my secret'
    google:
      clientId: 'env(GOOGLE_CLIENTID)'
      clientSecret: 'env(GOOGLE_SECRET)'
      redirectUri: 'http://localhost:3001/signin/google/cb'
    facebook:
      clientId: 'env(FACEBOOK_CLIENTID)'
      clientSecret: 'env(FACEBOOK_SECRET)'
      redirectUri: 'http://localhost:3001/signin/facebook/cb'
    github:
      clientId: 'env(GITHUB_CLIENTID)'
      clientSecret: 'env(GITHUB_SECRET)'
      redirectUri: 'http://localhost:3001/signin/github/cb'
    linkedin:
      clientId: 'env(LINKEDIN_CLIENTID)'
      clientSecret: 'env(LINKEDIN_SECRET)'
      redirectUri: 'http://localhost:3001/signin/linkedin/cb'
    twitter:
      clientId: 'env(TWITTER_CLIENTID)'
      clientSecret: 'env(TWITTER_SECRET)'
      redirectUri: 'http://localhost:3001/signin/twitter/cb'

