import { PasswordService } from './password.service';

/**
 * Compare a plain text password and a hash to see if they match.
 *
 * @deprecated Use `PasswordService.verifyPassword()` instead.
 * @export
 * @param {string} plainTextPassword - The password in clear text.
 * @param {string} passwordHash - The password hash generated by the `hashPassword` function.
 * @returns {Promise<boolean>} True if the hash and the password match. False otherwise.
 */
export async function verifyPassword(plainTextPassword: string, passwordHash: string): Promise<boolean> {
  const service = new PasswordService();
  return service.verifyPassword(plainTextPassword, passwordHash);
}
